apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
      imageregistry: "https://hub.docker.com/"
      buildurl: "https://jenkins.joindevops.com/expense/backend/build/67"
spec:
  containers:
  - name: nginx
    image: nginx