apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
